version: '3.5'
services:
  # server:
  #   build:
  #     context: ./webServer
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "${EXTERNAL_PORT}:${PORT}"
  #   environment:
  #     - NODE_ENV=dev
  #     - PORT=${PORT}
  #     - MICROSERVICE_LOGIN_HOST=microservice_login
  #   volumes:
  #     - ./webServer:/usr/src/app
  #   restart: always
  #   depends_on:
  #     - mongo
  microservice_login:
    build:
      context: ../
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=dev
      - PORT=${PORT}
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_HOST=mongo
    ports:
      - "${EXTERNAL_PORT}:${PORT}"
    volumes:
      - ../:/usr/src/app
    restart: always
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodbdata:/data/db

  admin-mongo:
    # mongodb://ROMAN:12345@mongo
    image: adicom/admin-mongo
    ports:
      - "${ADMIN_MONGO_PORT}:${ADMIN_MONGO_PORT}"
    environment:
      - PORT=${ADMIN_MONGO_PORT}
      - HOST=mongo
    depends_on:
      - mongo

volumes:
  mongodbdata: